sudo: required
language: node_js
node_js:
  - 5
services:
  - docker
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - npm install -g bower
  - bower install
  - docker build -t improvjaa/jaa-ee .
script:
  - docker push improvjaa/jaa-ee
after_script:
  - docker logout